### PR TITLE
Bump to 3.5.1

### PR DESCRIPTION
**Pull request by everdark**
The R package needs to bump to 3.5.1 as well.

### CODE REVIEW

**Comment by cpsievert** [comment]
Thanks, but the master branch appears to be on 3.5.1?

**Comment by everdark** [comment]
I thought the R package is still using `3.5.0` as the path?
So it will result in the package download `3.5.1` while the generated path pointing to `3.5.0`. Hence error.

**Comment by cpsievert** [comment]
Ohhh yes, thanks for catching that -- it was including 3.5.1, but marking the R HTML dependency as 3.5.0

**Comment by cpsievert** [comment]
Oh shoot, I should've asked you to sign our contributor agreement before merging would you mind filling out either the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement as appropriate? You can send the signed copy to jj@rstudio.com.

(Otherwise, I'll have to revert the merge)

**Comment by everdark** [comment]
> Oh shoot, I should've asked you to sign our contributor agreement before merging --- would you mind filling out either the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement as appropriate? You can send the signed copy to [jj@rstudio.com](mailto:jj@rstudio.com) (and please attach me, [carson@rstudio.com](mailto:carson@rstudio.com))
> 
> (Otherwise, I'll have to revert the merge)

Just sent. :)

**Comment by cpsievert** [comment]
Thank you!

**Pull request merged**
